{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "soc4kafka.fullname" . }}
  labels:
    {{- include "soc4kafka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 13133 }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "soc4kafka.selectorLabels" . | nindent 4 }}
{{- end }}
